### PR TITLE
Update to Julia 1.0

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Updating to

- Julia 1.0
- CxxWrap 0.8.1
- xtensor-julia 0.6.0 (already updated to Julia 1.0)

and general cleanup of the CI.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cc @barche  I am having some link issues with `libcxxwrap-julia` on windows.

This appears to be a `mingw` vs `visual studio` problem.

**Comment by SylvainCorlay** [comment]
Oh, this is a mingw vs visual studio problem.

**Comment by SylvainCorlay** [comment]
It seems that the last release of CxxWrap has binaries for MSVC (cf https://github.com/JuliaInterop/libcxxwrap-julia/releases), but it is not listed in the dictionary https://github.com/JuliaInterop/CxxWrap.jl/blob/master/deps/build.jl#L17.

Maybe it is a time for this CI to test Xtensor.jl with mingw instead of msvc.

**Comment by SylvainCorlay** [comment]
Could have a successful build and test with msys2.

**Comment by barche** [comment]
Yes, the build.jl is generated automatically by BinaryBuilder, which only runs cross compilers. I do think it would be nice to be able to supply binaries from Appveyor, but I thing BinaryBuilder wants to stick with the cross-compile approach.

I upload the MSVC binaries from the libcxxwrap-julia Appveyor tests since I had this deploy mechanism still from the pre-Julia 1.0 days, and maybe the binaries can be useful someday (thinking of QML.jl, which I anticipate will be hard to cross-compile).

**Pull request merged**
