### PR TITLE
WIP - Allow for not vendoring xtensor

### PR DESCRIPTION
**Pull request by SylvainCorlay**
In this PR we enable the option to not vendor xtensor and friends into Xtensor.jl with an environment variable, just like with the JLCXX_DIR in CxxWrap.jl.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
cc @barche

In this PR we enable the option to not vendor xtensor and friends into Xtensor.jl with an environment variable, just like with the JLCXX_DIR in CxxWrap.jl.

**Comment by SylvainCorlay** [comment]
This appears to be working locally but failing on the CI.

```
ERROR: LoadError: MethodError: no method matching (::getfield(CxxWrap, 
Symbol("#map_c_arg_type#4")))(::Tuple{Core.Compiler.Pair{Int64,Any},Tuple{Int64,Int64}})
```

**Comment by SylvainCorlay** [comment]
cc @barche do you have an idea of why using an external libcxxwrap (by seting the `JLCXX_DIR` environment variable) fails?

This is targetting the stable version of CxxWrap and the corresponding version of `libcxxwrap-julia`.

**Comment by barche** [comment]
Not sure what's going on, this looks like a symptom from a memory error somewhere, maybe a debug build will trigger an assertion somewhere?

**Pull request closed without merging**
