### PR TITLE
Add appveyor build

### PR DESCRIPTION
**Pull request by SylvainCorlay**
~~Cf: https://discourse.julialang.org/t/embedding-windows-binaries/3352~~

Using some link_directories and CMAKE_INSTALL_RPATH_USE_LINK_PATH I could get the build to work with libLLVM.

Now I have a windows-only issue with CxxWrap symbols....

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Using some `link_directories` and `CMAKE_INSTALL_RPATH_USE_LINK_PATH` I could get the build to work with libLLVM.

Now I have a windows-only issue with CxxWrap symbols....

**Comment by SylvainCorlay** [comment]
cc @barche

**Comment by SylvainCorlay** [comment]
So `CxxWrap` appears not to be relocatable. When I install julia in a different directory than the one used by the CxxWrap CI producing the binaries it complains that `C:/projects/julia/lib/libjulia.dll.a` is missing.

`NMAKE : fatal error U1073: don't know how to make 'C:\projects\julia\lib\libjulia.dll.a'`

**Comment by barche** [comment]
True, the easiest way around this for now is to set the `BUILD_ON_WINDOWS` environment to 1 when installing CxxWrap for now.

**Comment by SylvainCorlay** [comment]
Gotcha. Thanks. Quick question, is it really necessary to compile these, or could `CxxWrap` become header-only eventually?

**Pull request merged**
